name: app
type: "java:11"
disk: 1024
hooks:
    build: mvn clean package
relationships:
    database: "db:mongodb"
web:
    commands:
        start: java -jar $JAVA_OPTS target/client.jar --server.port=$PORT
