- name: user
  type: "java:11"
  source:
    root: user
  disk: 1024
  hooks:
    build: ./mvnw package -DskipTests
  relationships:
    database: "db:postgresql"
  web:
    commands:
      start: java -jar $JAVA_OPTS -Dquarkus.http.port=$PORT target/user-1.0-SNAPSHOT-runner.jar
- name: app
  type: "java:11"
  disk: 1024
  hooks:
    build: mvn clean package
  relationships:
    database: "db:mongodb"
  web:
    commands:
      start: java -jar $JAVA_OPTS target/client.jar --server.port=$PORT
