name: user
type: "java:11"
disk: 1024
hooks:
    build: ./mvnw package -DskipTests
relationships:
    database: "db:postgresql"
web:
    commands:
        start: java -jar $JAVA_OPTS -Dquarkus.http.port=$PORT target/user-1.0-SNAPSHOT-runner.jar
